dist: trusty
sudo: false
language: cpp

#
# Prepare build
#
before_script:
  # NOTE: gtest install workaround
  - cd /usr/src/gtest
  - sudo cmake . -DBUILD_SHARED_LIBS=ON
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
  # -- workaround end
  - mkdir build
  - cd build

#
# More complete test matrix
#
matrix:
  include:

    #
    # Testing for white spaces
    #
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libgtest-dev', 'cmake', 'cmake-data', 'binutils-gold']
      env:
        - TEST="Whitespace Checker"
      script:
        - |
          if [[ -n $(git diff-tree --check $(git hash-object -t tree /dev/null) HEAD) ]]; then
            echo "Remove whitespaces before submitting..."
            echo ""
            echo "Git check results:"
            echo ""
            git diff-tree --check $(git hash-object -t tree /dev/null) HEAD
            exit -1
          fi

    #
    # Coverage
    #
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libgtest-dev', 'cmake', 'cmake-data']
      env:
        - TEST="Coverage (C++14, C++17)"
      script:
        - cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DENABLE_COVERAGE:BOOL=TRUE -DENABLE_CPP17:BOOL=TRUE
        - make -j2
        - ctest --output-on-failure
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7

    #
    # Testing gcc 5
    #
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libgtest-dev', 'cmake', 'cmake-data']
      env:
        - TEST="g++-5 (C++14, UBSAN, ASAN)"
      script:
        - cmake .. -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_BUILD_TYPE=Debug
        - make -j2
        - ctest --output-on-failure

    #
    # Testing gcc 6
    #
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libgtest-dev', 'cmake', 'cmake-data']
      env:
        - TEST="g++-6 (C++14, UBSAN, ASAN)"
      script:
        - cmake .. -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_BUILD_TYPE=Debug
        - make -j2
        - ctest --output-on-failure

    #
    # Testing gcc 7
    #
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libgtest-dev', 'cmake', 'cmake-data']
      env:
        - TEST="g++-7 (C++14, C++17, UBSAN, ASAN)"
      script:
        - cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=Debug -DENABLE_CPP17:BOOL=TRUE
        - make -j2
        - ctest --output-on-failure

    #
    # Testing clang 5
    #
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['g++-6', 'clang-5.0', 'libgtest-dev', 'cmake', 'cmake-data']
      env:
        - TEST="clang++-5.0 (C++14, C++17, UBSAN, ASAN)"
      script:
        - cmake .. -DCMAKE_CXX_COMPILER=clang++-5.0 -DCMAKE_BUILD_TYPE=Debug -DENABLE_CPP17:BOOL=TRUE
        - make -j2
        - ctest --output-on-failure
